-- StrideSense Supabase baseline schema
-- Apply with the Supabase CLI or SQL editor after creating the project.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'privacy_level') then
    create type public.privacy_level as enum ('public', 'friends', 'private');
  end if;
  if not exists (select 1 from pg_type where typname = 'club_role') then
    create type public.club_role as enum ('owner', 'admin', 'member');
  end if;
  if not exists (select 1 from pg_type where typname = 'challenge_type') then
    create type public.challenge_type as enum ('distance', 'count', 'time');
  end if;
  if not exists (select 1 from pg_type where typname = 'challenge_status') then
    create type public.challenge_status as enum ('upcoming', 'active', 'completed', 'cancelled');
  end if;
  if not exists (select 1 from pg_type where typname = 'workout_status') then
    create type public.workout_status as enum ('running', 'paused', 'completed', 'abandoned');
  end if;
  if not exists (select 1 from pg_type where typname = 'activity_type') then
    create type public.activity_type as enum ('run', 'walk', 'cycle', 'workout');
  end if;
  if not exists (select 1 from pg_type where typname = 'workout_source') then
    create type public.workout_source as enum ('mobile', 'healthkit', 'health_connect', 'manual', 'gps');
  end if;
  if not exists (select 1 from pg_type where typname = 'workout_event_type') then
    create type public.workout_event_type as enum ('start', 'pause', 'resume', 'complete');
  end if;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  first_name text not null default '',
  last_name text not null default '',
  bio text,
  avatar_url text,
  city text,
  privacy_level public.privacy_level not null default 'public',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.private_user_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  phone text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clubs (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.club_members (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.club_role not null default 'member',
  joined_at timestamptz not null default timezone('utc', now()),
  unique (club_id, user_id)
);

create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  club_id bigint references public.clubs(id) on delete set null,
  title text not null,
  description text,
  type public.challenge_type not null default 'distance',
  target_value numeric(10, 2) not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  status public.challenge_status not null default 'upcoming',
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.challenge_participants (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null references public.challenges(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default timezone('utc', now()),
  unique (challenge_id, user_id)
);

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_id bigint references public.challenges(id) on delete set null,
  activity_type public.activity_type not null default 'run',
  status public.workout_status not null default 'running',
  started_at timestamptz not null,
  ended_at timestamptz,
  duration_sec integer,
  distance_m numeric(10, 2),
  avg_pace_sec_per_km numeric(10, 2),
  calories_kcal numeric(10, 2),
  category text,
  source public.workout_source not null default 'mobile',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.workout_events (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  event_type public.workout_event_type not null,
  event_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.workout_samples (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  captured_at timestamptz not null,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  altitude_m numeric(8, 2),
  distance_m numeric(10, 2),
  pace_sec_per_km numeric(10, 2),
  heart_rate_bpm integer,
  steps integer,
  calories_kcal numeric(10, 2),
  source public.workout_source not null default 'gps',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.idempotency_keys (
  id bigint generated by default as identity primary key,
  key_value text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  response_code integer not null,
  response_body jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null
);

create index if not exists idx_private_user_data_email on public.private_user_data (email);
create index if not exists idx_club_members_user_id on public.club_members (user_id);
create index if not exists idx_challenges_status on public.challenges (status);
create index if not exists idx_workouts_user_time on public.workouts (user_id, started_at desc);
create index if not exists idx_workouts_status on public.workouts (status);
create index if not exists idx_workout_events_workout_time on public.workout_events (workout_id, event_at);
create index if not exists idx_workout_samples_workout_time on public.workout_samples (workout_id, captured_at);
create index if not exists idx_idempotency_expiry on public.idempotency_keys (expires_at);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists private_user_data_set_updated_at on public.private_user_data;
create trigger private_user_data_set_updated_at
before update on public.private_user_data
for each row execute function public.set_updated_at();

drop trigger if exists workouts_set_updated_at on public.workouts;
create trigger workouts_set_updated_at
before update on public.workouts
for each row execute function public.set_updated_at();

create or replace function public.handle_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, first_name, last_name)
  values (
    new.id,
    nullif(lower(regexp_replace(split_part(new.email, '@', 1), '[^a-z0-9._]', '', 'g')), ''),
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', '')
  )
  on conflict (id) do nothing;

  insert into public.private_user_data (user_id, email, phone)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (user_id) do update
    set email = excluded.email,
        phone = coalesce(excluded.phone, public.private_user_data.phone);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_auth_user_created();

create or replace function public.handle_auth_user_updated()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.private_user_data
     set email = new.email,
         phone = coalesce(nullif(new.raw_user_meta_data ->> 'phone', ''), phone)
   where user_id = new.id;

  update public.profiles
     set first_name = coalesce(new.raw_user_meta_data ->> 'first_name', first_name),
         last_name = coalesce(new.raw_user_meta_data ->> 'last_name', last_name)
   where id = new.id;

  return new;
end;
$$;

drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
after update on auth.users
for each row execute function public.handle_auth_user_updated();

create or replace function public.current_user_dashboard()
returns table (
  total_distance_m numeric,
  workouts_count bigint
)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(sum(distance_m), 0) as total_distance_m,
    count(*) as workouts_count
  from public.workouts
  where user_id = auth.uid()
    and status = 'completed';
$$;

create or replace function public.leaderboard_distance(period text default 'weekly')
returns table (
  user_id uuid,
  display_name text,
  total_distance_m numeric,
  avg_pace_sec_per_km numeric,
  active_days bigint
)
language sql
security definer
set search_path = public
as $$
  with filtered as (
    select *
    from public.workouts
    where status = 'completed'
      and (
        period = 'monthly' and started_at >= timezone('utc', now()) - interval '30 days'
        or period <> 'monthly' and started_at >= timezone('utc', now()) - interval '7 days'
      )
  )
  select
    w.user_id,
    trim(concat(p.first_name, ' ', p.last_name)) as display_name,
    coalesce(sum(w.distance_m), 0) as total_distance_m,
    coalesce(avg(w.avg_pace_sec_per_km), 0) as avg_pace_sec_per_km,
    count(distinct date(w.started_at)) as active_days
  from filtered w
  join public.profiles p on p.id = w.user_id
  group by w.user_id, p.first_name, p.last_name
  order by total_distance_m desc, active_days desc, avg_pace_sec_per_km asc;
$$;

alter table public.profiles enable row level security;
alter table public.private_user_data enable row level security;
alter table public.clubs enable row level security;
alter table public.club_members enable row level security;
alter table public.challenges enable row level security;
alter table public.challenge_participants enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_events enable row level security;
alter table public.workout_samples enable row level security;
alter table public.idempotency_keys enable row level security;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "private_user_data_select_own" on public.private_user_data;
create policy "private_user_data_select_own"
on public.private_user_data
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "private_user_data_update_own" on public.private_user_data;
create policy "private_user_data_update_own"
on public.private_user_data
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "clubs_select_authenticated" on public.clubs;
create policy "clubs_select_authenticated"
on public.clubs
for select
to authenticated
using (true);

drop policy if exists "clubs_insert_authenticated" on public.clubs;
create policy "clubs_insert_authenticated"
on public.clubs
for insert
to authenticated
with check (auth.uid() = created_by);

drop policy if exists "club_members_select_authenticated" on public.club_members;
create policy "club_members_select_authenticated"
on public.club_members
for select
to authenticated
using (true);

drop policy if exists "club_members_insert_self" on public.club_members;
create policy "club_members_insert_self"
on public.club_members
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "club_members_delete_self" on public.club_members;
create policy "club_members_delete_self"
on public.club_members
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "challenges_select_authenticated" on public.challenges;
create policy "challenges_select_authenticated"
on public.challenges
for select
to authenticated
using (true);

drop policy if exists "challenges_insert_authenticated" on public.challenges;
create policy "challenges_insert_authenticated"
on public.challenges
for insert
to authenticated
with check (auth.uid() = created_by);

drop policy if exists "challenge_participants_select_authenticated" on public.challenge_participants;
create policy "challenge_participants_select_authenticated"
on public.challenge_participants
for select
to authenticated
using (true);

drop policy if exists "challenge_participants_insert_self" on public.challenge_participants;
create policy "challenge_participants_insert_self"
on public.challenge_participants
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "workouts_select_own" on public.workouts;
create policy "workouts_select_own"
on public.workouts
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "workouts_insert_own" on public.workouts;
create policy "workouts_insert_own"
on public.workouts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "workouts_update_own" on public.workouts;
create policy "workouts_update_own"
on public.workouts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "workout_events_select_own" on public.workout_events;
create policy "workout_events_select_own"
on public.workout_events
for select
to authenticated
using (
  exists (
    select 1
    from public.workouts w
    where w.id = workout_id
      and w.user_id = auth.uid()
  )
);

drop policy if exists "workout_events_insert_own" on public.workout_events;
create policy "workout_events_insert_own"
on public.workout_events
for insert
to authenticated
with check (
  exists (
    select 1
    from public.workouts w
    where w.id = workout_id
      and w.user_id = auth.uid()
  )
);

drop policy if exists "workout_samples_select_own" on public.workout_samples;
create policy "workout_samples_select_own"
on public.workout_samples
for select
to authenticated
using (
  exists (
    select 1
    from public.workouts w
    where w.id = workout_id
      and w.user_id = auth.uid()
  )
);

drop policy if exists "workout_samples_insert_own" on public.workout_samples;
create policy "workout_samples_insert_own"
on public.workout_samples
for insert
to authenticated
with check (
  exists (
    select 1
    from public.workouts w
    where w.id = workout_id
      and w.user_id = auth.uid()
  )
);

drop policy if exists "idempotency_keys_own" on public.idempotency_keys;
create policy "idempotency_keys_own"
on public.idempotency_keys
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "avatar_read_public" on storage.objects;
create policy "avatar_read_public"
on storage.objects
for select
to public
using (bucket_id = 'avatars');

drop policy if exists "avatar_upload_own" on storage.objects;
create policy "avatar_upload_own"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and auth.uid()::text = split_part(name, '/', 1)
);

drop policy if exists "avatar_update_own" on storage.objects;
create policy "avatar_update_own"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and auth.uid()::text = split_part(name, '/', 1)
)
with check (
  bucket_id = 'avatars'
  and auth.uid()::text = split_part(name, '/', 1)
);

drop policy if exists "avatar_delete_own" on storage.objects;
create policy "avatar_delete_own"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and auth.uid()::text = split_part(name, '/', 1)
);
